### ISSUE TITLE
Groonga can't build with msgpack 1.0.1

### ISSUE THREAD

**Issue by cosmo0920** [groonga/groonga#328]
Homebrew provides too latest msgpack package. :<
 
```log
 CXXLD    libgroonga.la
Undefined symbols for architecture x86_64:
  "_msgpack_pack_raw", referenced from:
      _grn_output_str in output.o
      _grn_output_geo_point in output.o
      _grn_output_envelope in output.o
  "_msgpack_pack_raw_body", referenced from:
      _grn_output_str in output.o
      _grn_output_geo_point in output.o
      _grn_output_envelope in output.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [libgroonga.la] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

```bash
$ pkg-config --modversion msgpack
1.0.1
```

I found this issue in [this pull request](https://github.com/Homebrew/homebrew/pull/38167) for updating Groonga 5.0.1.

Complete build log is here: https://dl.dropboxusercontent.com/u/36753409/HomebrewLogs/02.make-groonga-5.0.1.log

**Comment by cosmo0920** [comment]
Thanks!! I've confirmed build success at latest revision homebrew!! :beer:

**Comment by kou** [comment]
Thanks for confirming it.
